"""
Integration Risk Detector

Runs ONLY on psychedelic and high-intensity meditation entries (ego_strength_signal <= 2).
Detects spiritual inflation, ego-dissolution without re-grounding, shadow bypassing,
and premature closure.

This is NOT a clinical safety tool. It is a symbolic integration compass.
The output should never be surfaced as a warning or diagnosis —
frame it as "integration guidance" in the UI.

RECOMMENDED TEMPERATURE: 0.2
Rationale: Risk detection must be consistent and conservative. False negatives
(missing a real inflation signal) are worse than false positives here.
Low temperature keeps the model grounded in what's actually in the text.

Called by: services/integration.py
Trigger condition: entry_type == 'psychedelic' OR
                  (entry_type == 'meditation' AND ego_strength_signal <= 2)
"""


def build_integration_risk_prompt(
    raw_text: str,
    entry_type: str,
    jungian_summary: str,
    ego_strength_signal: int,
    recent_entries_summaries: list[str],
) -> str:
    """
    Build the integration risk assessment prompt.

    Args:
        raw_text: The original entry text.
        entry_type: 'psychedelic' | 'meditation'
        jungian_summary: The summary already generated by extractor.py
        ego_strength_signal: The ego strength score (1–6) from extractor.py
        recent_entries_summaries: Last 3–5 entry summaries for context on
                                   whether inflation is new or ongoing.

    Returns:
        Prompt string for the integration risk call.
    """
    recent_block = ""
    if recent_entries_summaries:
        recent_block = "Recent entry summaries (for context on whether this pattern is new):\n"
        for i, s in enumerate(recent_entries_summaries, 1):
            recent_block += f"{i}. {s}\n"
    else:
        recent_block = "Recent entry summaries: None available."

    return f"""You are a Jungian analyst assessing the integration risk of a recent {entry_type} entry.

Your task is not diagnosis. Your task is to identify whether the symbolic content of this experience
carries patterns that — if left unexamined — typically interfere with genuine psychological integration.

---
THE RISKS YOU ARE SCANNING FOR

SPIRITUAL INFLATION
The ego has encountered a powerful archetypal energy and begun to identify WITH it rather than
relate TO it. Signs: the person believes they have been chosen, that they now possess special knowledge
or power, that they have "solved" themselves or the world, that they have merged with God/universe/death
and returned transformed in a way that places them above ordinary life.
Inflation is not growth. It is the ego inflating to match the archetype's size instead of standing
in relationship to it.

EGO DISSOLUTION WITHOUT RE-GROUNDING
The ego was suspended during the experience (normal) but shows no signs of re-cohering afterward.
Signs: the entry reads as fractured, boundary-less, unable to locate a stable "I", ongoing
derealisation, the person cannot locate themselves in time or space after the experience.
Brief dissolution is normal. Persistent dissolution is a signal.

SHADOW BYPASSING
Shadow bypassing has two distinct forms. Do not conflate them.

Form A — Avoidance Bypass: The experience was intensely positive or transcendent, but
pre-existing Shadow material (visible in recent entries) is conspicuously absent from
this entry. The positive experience appears to have routed around, not through, the shadow.
Transcendence that leaves the wound intact is bypass.

Form B — Golden Shadow Bypass: The experience was intensely positive, but the positive
energy belongs to a Golden Shadow complex — disowned strength, creativity, or vitality
the ego has not yet claimed. The risk here is NOT that the experience was positive.
The risk is that the EGO IS CLAIMING CREDIT for energy that is archetypal, not personal.
Signs: "I finally understand my purpose", "I realized I am a healer/teacher/visionary",
"I felt infinite love and I was the source of it."
The experience of meeting one's Golden Shadow is genuine and often profound — but the ego
that immediately says "this is me, I have this now" has inflated, not integrated.
True integration of Golden Shadow is slower: it involves standing in relationship with the
energy, not identifying with it on contact.

Assess which form is present, or both, or neither. Do not flag a positive experience as
bypass simply because it is positive. Specificity is required.

PREMATURE CLOSURE
The person has declared the work "done." The psyche rarely agrees.
Signs: "I finally understand everything", "I've integrated my shadow", "I'm healed now."
These declarations in the immediate aftermath of an intense experience are almost always
the ego managing the experience, not the unconscious completing its work.

---
ENTRY DATA

Entry type: {entry_type}
Ego strength signal: {ego_strength_signal}/6
Jungian summary (from primary extractor): {jungian_summary}

{recent_block}

Original entry text:
---
{raw_text}
---

---
ASSESSMENT INSTRUCTIONS

For each of the four risk categories, determine:
- present: true | false
- severity: "low" | "moderate" | "high" (only if present is true, else null)
- evidence: 1–2 sentences citing specific content from the entry (only if present is true, else null)

Then produce:
- integration_guidance: 2–3 sentences of grounded Jungian guidance for how to approach
  integration of THIS specific experience. Not generic advice. Specific to what's in the entry.
  Do not catastrophize. Do not reassure. Point toward the actual symbolic work.
- overall_risk_level: "none" | "low" | "moderate" | "high"
  (aggregate assessment — use the highest severity present, but downgrade if only one mild flag)

---
RETURN FORMAT
Return ONLY valid JSON. No markdown. No preamble.

{{
  "spiritual_inflation": {{
    "present": bool,
    "severity": str | null,
    "evidence": str | null
  }},
  "ego_dissolution_without_regrounding": {{
    "present": bool,
    "severity": str | null,
    "evidence": str | null
  }},
  "shadow_bypassing": {{
    "present": bool,
    "form": str | null,
    "severity": str | null,
    "evidence": str | null
  }},
  "premature_closure": {{
    "present": bool,
    "severity": str | null,
    "evidence": str | null
  }},
  "integration_guidance": str,
  "overall_risk_level": str
}}
"""
